<?php 
/**
 * Registering all hardcoded theme strings for translation with Polylang
 */

add_action('init', 'polylang_register_theme_strings');
function polylang_register_theme_strings() {
    if (function_exists('pll_register_string')) {
        pll_register_string('clockwise', 'Large');
        pll_register_string('clockwise', 'Small');
        pll_register_string('clockwise', 'Desk Size');
        pll_register_string('clockwise', 'Number of desks');
        pll_register_string('clockwise', 'Enquire Now');
        pll_register_string('clockwise', 'Learn more');
        pll_register_string('clockwise', 'Apply');
        pll_register_string('clockwise', 'Address');
        pll_register_string('clockwise', 'Vacancies');
        pll_register_string('clockwise', 'Read more');
        pll_register_string('clockwise', 'Take virtual tour');
        pll_register_string('clockwise', 'km away');
        pll_register_string('clockwise', 'Book a tour');
        pll_register_string('clockwise', 'Book now');
        pll_register_string('clockwise', 'Access the Member Portal below to book your meeting');
        pll_register_string('clockwise', 'Book a meeting room');
        pll_register_string('clockwise', 'Make an enquiry');
        pll_register_string('clockwise', 'Member Login');
        pll_register_string('clockwise', 'Events for:');
        pll_register_string('clockwise', 'No vacancies could be found');
        pll_register_string('clockwise', 'Locations');
        pll_register_string('clockwise', 'All locations');
        pll_register_string('clockwise', 'All memberships');
        pll_register_string('clockwise', 'Become a member');
        pll_register_string('clockwise', 'View all locations');
        pll_register_string('clockwise', 'Full newsfeed');
        pll_register_string('clockwise', 'Overview');
        pll_register_string('clockwise', 'Full client list');
        pll_register_string('clockwise', 'Watch video');
        pll_register_string('clockwise', 'Clockwise Articles');
        pll_register_string('clockwise', 'Clockwise Events');
        pll_register_string('clockwise', 'Back to top');
        pll_register_string('clockwise', 'Back');
        pll_register_string('clockwise', 'Related articles');
        pll_register_string('clockwise', 'Share article');
        pll_register_string('clockwise', 'Share vacancy');
        pll_register_string('clockwise', 'Share');
        pll_register_string('clockwise', 'per hour');
        pll_register_string('clockwise', 'Floor');
        pll_register_string('clockwise', 'Watch Intro Video');
        pll_register_string('clockwise', 'Featured Article');
        pll_register_string('clockwise', 'Featured Event');
        pll_register_string('clockwise', 'Career Case Study');
        pll_register_string('clockwise', 'Central Office');
        pll_register_string('clockwise', 'About clockwise');
        pll_register_string('clockwise', 'Contact Info');
        pll_register_string('clockwise', 'Membership Enquiry Form');
        pll_register_string('clockwise', 'Enquiry Form');
        pll_register_string('clockwise', 'Referral Form');
        pll_register_string('clockwise', 'Referee Form');
        pll_register_string('clockwise', 'You have been referred to Clockwise by: ');
        pll_register_string('clockwise', 'Please complete the form below and a member of our team will be in touch.');
        pll_register_string('clockwise', 'Contact Form');
        pll_register_string('clockwise', 'No. of seats');
        pll_register_string('clockwise', 'No. of people');
        pll_register_string('clockwise', 'Find a room');
        pll_register_string('clockwise', 'seats');
        pll_register_string('clockwise', 'Search');
        pll_register_string('clockwise', 'Reset filter');
        pll_register_string('clockwise', 'Select region');
        pll_register_string('clockwise', 'Select location');
        pll_register_string('clockwise', 'Select a job type');
        pll_register_string('clockwise', 'Region');
        pll_register_string('clockwise', 'Location');
        pll_register_string('clockwise', 'Job type');
        pll_register_string('clockwise', 'Load more');
        pll_register_string('clockwise', 'Sort by');
        pll_register_string('clockwise', 'Most recently added');
        pll_register_string('clockwise', 'Alphabetically');
        pll_register_string('clockwise', 'All types');
        pll_register_string('clockwise', 'All regions');
        pll_register_string('clockwise', 'All locations');
        pll_register_string('clockwise', 'Business Name');
        pll_register_string('clockwise', 'Clockwise in');
        pll_register_string('clockwise', 'Location Index');
        pll_register_string('clockwise', 'View Location');
        pll_register_string('clockwise', 'Book as member');
        pll_register_string('clockwise', 'Book as non-member');
        pll_register_string('clockwise', 'Book room as a non-member');
        pll_register_string('clockwise', 'No meeting rooms could be found');
        pll_register_string('clockwise', 'Year');
        pll_register_string('clockwise', 'Years');
        pll_register_string('clockwise', 'Traditional');
        pll_register_string('clockwise', 'Annual Expenditure');
        pll_register_string('clockwise', 'Key');
        pll_register_string('clockwise', 'Model Type');
        pll_register_string('clockwise', 'Capital outlay');
        pll_register_string('clockwise', 'Rent');
        pll_register_string('clockwise', 'Meeting room hire');
        pll_register_string('clockwise', 'Services & Utilities');
        pll_register_string('clockwise', 'Utility costs');
        pll_register_string('clockwise', 'Business rates');
        pll_register_string('clockwise', 'Reception staff');
        pll_register_string('clockwise', 'Electricity, internet');
        pll_register_string('clockwise', 'Repairs and maintenance');
        pll_register_string('clockwise', 'Cleaning');
        pll_register_string('clockwise', 'Time Period');
        pll_register_string('clockwise', 'Proceed');
        pll_register_string('clockwise', 'New Search');
        pll_register_string('clockwise', 'Flexible office');
        pll_register_string('clockwise', 'Traditional leases');
        pll_register_string('clockwise', 'Setup costs');
        pll_register_string('clockwise', 'Operating costs');
        // pll_register_string('clockwise', 'Fit out, furniture, etc');
        pll_register_string('clockwise', 'Fit out');
        pll_register_string('clockwise', 'Furniture');
        pll_register_string('clockwise', 'Transaction costs');
        pll_register_string('clockwise', 'Dilapidations');
        pll_register_string('clockwise', 'All-inclusive');
        pll_register_string('clockwise', 'in total');
        pll_register_string('clockwise', 'Total monthly');
        pll_register_string('clockwise', 'Total costs over the period');
        pll_register_string('clockwise', 'per seat/month');
        pll_register_string('clockwise', 'month');
        pll_register_string('clockwise', 'Total savings with a Flexible office:');
        pll_register_string('clockwise', 'can be saved or invested in building your business!');
        pll_register_string('clockwise', 'Including setup costs spread over 36 months');
        pll_register_string('clockwise', 'Including setup costs spread over 24 months');
        pll_register_string('clockwise', 'Including setup costs spread over 12 months');
        pll_register_string('clockwise', 'Our events are currently on hold until we’re able to bring people together again.');
        pll_register_string('clockwise', 'Download a Brochure');
        pll_register_string('clockwise', 'Request a Brochure');
        pll_register_string('clockwise', 'Fill out your details below and we’ll send the brochure to your inbox.');
        pll_register_string('clockwise', 'Cookie Name');
        pll_register_string('clockwise', 'Purpose');
        pll_register_string('clockwise', 'Expiry');
    }
}


?>